### ISSUE TITLE
Support default field values other than None

### ISSUE THREAD

**Issue by doomsuckle** [s-knibbs/dataclasses-jsonschema#30]
There's a small issue that pops up when you have non-None default values. I see the issues happens on line 290 when it does `data.get(mapped_field)` but I'm not sure the best way to resolve. (failed hard on test_embeddable_json_schema)

@dataclass
class DefaultVal(JsonSchemaMixin):
    a: int
    b: Optional[int] = 5

should pass:

assert DefaultVal.from_dict({'a': 1}) == DefaultVal(a=1)

**Comment by s-knibbs** [comment]
Yeah, it's not handling field defaults correctly at the moment and the default value is not currently being included in the generated schema

**Comment by s-knibbs** [comment]
Updated the README for now to document this limitation.
