### ISSUE TITLE
Decoding json fails if default nested classes are used

### ISSUE THREAD

**Issue by mathPi** [s-knibbs/dataclasses-jsonschema#41]
ps: Sorry for the change of names, I made a mistake

I want to load a class that contains a class from a dict. But I get the error "object` has no attribute 'get'".

Example:
```
@dataclass
class nested(JsonSchemaMixin):
      a: str = "hi"
      b: int = 4
@dataclass
class test_schema(JsonSchemaMixin):
            """description"""
            champ: nested = field(default=nested())
```
When I want to load with an empty dict:
```
print(test_schema.from_dict({}))
```

I have an error:
```
AttributeError: 'nested' object has no attribute 'get'
```

Do you have an idea ?
I have a solution, can I propose it in a pull request ?

**Comment by s-knibbs** [comment]
Thanks for reporting this. Looks like the issue is caused by the fact that the code is trying to decode the default value. I'm happy for you to send me a PR for this.

**Comment by s-knibbs** [comment]
This is also somewhat related to #42 since your example could be changed to:

```python
@dataclass
class test_schema(JsonSchemaMixin):
            champ: nested = field(default_factory=nested)
