### ISSUE TITLE
Fields with default_factory are included in required properties

### ISSUE THREAD

**Issue by s-knibbs** [s-knibbs/dataclasses-jsonschema#42]
Fields that use `default_factory` are included in the required schema arguments, so:

```python
@dataclass
class Config(JsonSchemaMixin):
    """A configuration class""
    some_mapping: Dict[str, str] = field(default_factory=dict)

pprint(Config.json_schema())
```

outputs the following:
```
{'$schema': 'http://json-schema.org/draft-06/schema#',
 'definitions': {},
 'description': 'A configuration class',
 'properties': {'some_mapping': {'additionalProperties': {'type': 'string'},
                                 'type': 'object'}},
 'required': ['some_mapping'],
 'type': 'object'}
```

**Comment by mathPi** [comment]
Hi, I had the same bug, I resolved it on my local repository. I can make a pull request. I also add issues with unions, inheritance, I corrected them in local, I can share with you.

**Comment by mathPi** [comment]
Hey, Are you sure it is fixed ? 
`
    @dataclass
    class ClassTest(JsonSchemaMixin):
        attri: List[str] = field(default_factory=lambda: ['val'])

    print(ClassTest.json_schema())

    assert ClassTest().attri == ['val']
    assert ClassTest().to_dict() == {'attri': ['val']}
    assert ClassTest.from_dict({}).attri == ['val']
`
In this case, attri is still required.
