### ISSUE TITLE
Generate dataclass from jsonschema feature

### ISSUE THREAD

**Issue by Benoss** [s-knibbs/dataclasses-jsonschema#49]
Would it be possible to generate Python from json schema ?
Usecase: I want to use dataclasses in my app but the jsonschema is generated by a third party.
Would be good if I could generate a model file with all the dataclasses from the jsonschema so that I can validate my data before sending it to their API.
I could write all the classes manually but being able to auto generate them would be a good thing!

**Comment by s-knibbs** [comment]
I agree that this would be a useful feature, but this would probably be better implemented as a separate tool to keep this library as lightweight as possible.

I don't really have any plans to do this however as I think dealing with all of the various jsonschema keywords would require a considerable amount of effort.
