### ISSUE TITLE
Support nullable fields

### ISSUE THREAD

**Issue by s-knibbs** [s-knibbs/dataclasses-jsonschema#57]
There should be an option to allow nullable fields. I propose the following api:

```python
@dataclass
class Address(JsonSchemaMixin):
    company: Optional[str] = field(default=None, metadata=dict(nullable=True))
    building: str
    street: str
    ...
```

There are a couple of ways to support nullable fields in JSON schema, either:

```json
{
  "properties": {
    "company": {"type": ["string", "null"]}
  }
}
```
or:
```json
{
  "properties": {
    "company": {"oneOf": [{"type": "string"}, {"type": "null"}]}
  }
}
```
The former is not supported in Swagger / OpenAPI though. OpenAPI 3 also supports the following:
```json
{
  "properties": {
    "company": {"type": "string", "nullable": true}
  }
}
```

**Comment by HHK1** [comment]
@s-knibbs 

I've encountered an issue with the Nullable type.

What I would like to achieve is to allow Null values to be passed during instantiation with `from_dict`, but that they remain filtered out. 

```
@dataclass
class WithOptional(JSONSchemaMixin):
    my_field: Optional[str]


WithOptional.from_dict({ "my_field": None }) # Error, None is not of type str

@dataclass
class WithNullable(JSONSchemaMixin):
    my_field: Nullable[str]

WithNullable.from_dict({ "my_field": None }) # Works
WithNullable.from_dict({ "my_field": None }).to_dict() # Includes { "my_field": None }, which also not what I want
```

Is there a way to achieve this somehow ? I understand the need for Nullable, but I don't get why optional would fail to init with an explicit null value.
