### ISSUE TITLE
Allow specification extensions

### ISSUE THREAD

**Issue by Garito** [s-knibbs/dataclasses-jsonschema#89]
Hi
I'm using the schema definition to generate the form at client side and I would like to use specification extensions:
https://swagger.io/specification/#specificationExtensions

For the field should be as simple as define x_label field in the metadata and would render as x-label in the json schema

I have more doubts about how to extend the schema itself since there are no class annotation that I can found but I would use it to define the list of fields in the form and the order with x-form = []

What do you think about this?

**Comment by s-knibbs** [comment]
I need to work on improving documentation but this is already possible with the following:

```python
@dataclass
class Obj(JsonSchemaMixin):
    some_field: str = field(metadata=JsonSchemaMeta(extensions={"label": "Some label"}))
```

See https://github.com/s-knibbs/dataclasses-jsonschema/blob/master/tests/test_core.py#L378 for another example of this.

**Comment by Garito** [comment]
Nice!
What about schema extensions?

**Comment by Garito** [comment]
What about the other properties like maximum and minimum?
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject

Hope don't bother you me asking all the time
