### ISSUE TITLE
fastjsonschema - compilation of validation function and its reuse

### ISSUE THREAD

**Issue by ZdenekM** [s-knibbs/dataclasses-jsonschema#97]
In order to fully take the advantage of fastjsonschema library, it would be necessary to compile the validation function and then reuse it for each validation (when ```from_dict``` is called). From code (https://github.com/s-knibbs/dataclasses-jsonschema/blob/2fd41a0b35591cf02016ba32787bd3dcf837c0d1/dataclasses_jsonschema/__init__.py#L27) it seem that ```validate``` function is used which combines compilation and validation into one step meaning that compilation is done repeatedly. What about storing compiled validation function somehow and reusing it for successive validations? It could be stored as a class method probably?

**Comment by s-knibbs** [comment]
Yeah, that's a red herring if you look in the [_validate method](https://github.com/s-knibbs/dataclasses-jsonschema/blob/2fd41a0b35591cf02016ba32787bd3dcf837c0d1/dataclasses_jsonschema/__init__.py#L410), it does actually use the compiled schema. That function should just be a no-op, it's there to keep the static analysis tools happy.

**Comment by ZdenekM** [comment]
Ok, thanks for clarification!
